version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres-python
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-python-db:/var/lib/postgresql/data
    restart: always